[keys]
new_tab = "cmd+t"
close_pane = "cmd+w"
split_vertical = "cmd+d"
split_horizontal = "cmd+shift+d"
cycle_pane_next = "cmd+]"
cycle_pane_previous = "cmd+["
next_tab = "alt+tab"
previous_tab = "alt+shift+tab"
switch_workspace = "cmd+1..9"
switch_tab = ""
prefix = "ctrl+b"
help = "prefix+?"
rename_tab = ""
focus_pane_left = ""
focus_pane_down = ""
focus_pane_up = ""
focus_pane_right = ""
